/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedLiveBookRouteImport } from './routes/_authenticated/live-book'
import { Route as AuthenticatedOutcomesRouteImport } from './routes/_authenticated/outcomes'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedReconRouteImport } from './routes/_authenticated/recon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveBookRoute = AuthenticatedLiveBookRouteImport.update({
  id: '/live-book',
  path: '/live-book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutcomesRoute = AuthenticatedOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconRoute = AuthenticatedReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/live-book': typeof AuthenticatedLiveBookRoute
  '/outcomes': typeof AuthenticatedOutcomesRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/recon': typeof AuthenticatedReconRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/live-book': typeof AuthenticatedLiveBookRoute
  '/outcomes': typeof AuthenticatedOutcomesRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/recon': typeof AuthenticatedReconRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/live-book': typeof AuthenticatedLiveBookRoute
  '/_authenticated/outcomes': typeof AuthenticatedOutcomesRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/recon': typeof AuthenticatedReconRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/live-book'
    | '/outcomes'
    | '/overview'
    | '/recon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/live-book'
    | '/outcomes'
    | '/overview'
    | '/recon'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit'
    | '/_authenticated/live-book'
    | '/_authenticated/outcomes'
    | '/_authenticated/overview'
    | '/_authenticated/recon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-book': {
      id: '/_authenticated/live-book'
      path: '/live-book'
      fullPath: '/live-book'
      preLoaderRoute: typeof AuthenticatedLiveBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outcomes': {
      id: '/_authenticated/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof AuthenticatedOutcomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recon': {
      id: '/_authenticated/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof AuthenticatedReconRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedLiveBookRoute: typeof AuthenticatedLiveBookRoute
  AuthenticatedOutcomesRoute: typeof AuthenticatedOutcomesRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedReconRoute: typeof AuthenticatedReconRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedLiveBookRoute: AuthenticatedLiveBookRoute,
  AuthenticatedOutcomesRoute: AuthenticatedOutcomesRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedReconRoute: AuthenticatedReconRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
